name:                graph-products
version:             0.1.0.0
github:              "vercadol/graph-products"
license:             BSD3
author:              "Veronika Dolanska"
maintainer:          "dolanskaverca@gmail.com"
copyright:           "2021 Veronika Dolanska"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/vercadol/graph-products#readme>

dependencies:
- base >= 4.7 && < 5
- containers

library:
  source-dirs: src

executables:
  example:
    main:                Graphviz.hs
    source-dirs:         examples
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Graphviz
    dependencies:
    - graph-products
    - graphviz
    - text

tests:
  graph-products-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - graph-products
    - hspec
    - QuickCheck
