name: test-graph-products
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        stack build
    - name: Run tests
      run: stack test
